//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public int PatientID { get; set; }

        [Required(ErrorMessage = "Please enter your first name")]
        [Display(Name = "First Name")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Please enter your last name")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter your date of birth")]
        [Display(Name = "Date of Birth")]
        [CustomValidation(typeof(Patient), "ValidateDateOfBirth")]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Please enter your sex")]
        [Display(Name= "Gender")]
        [RegularExpression("Male|Female", ErrorMessage= "Please enter Male or Female")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please enter your address")]
        [Display(Name = "Address")]

        public string Address { get; set; }
        [Required(ErrorMessage = "Please enter your phone number")]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Please enter a valid phone number")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Please enter your email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your date of Registration")]
        [Display(Name = "Date of Registration")]
        [CustomValidation(typeof(Patient), "ValidateDateOfRegistration")]
        public System.DateTime DateOfRegistration { get; set; }

        public static ValidationResult ValidateDateOfRegistration(DateTime dateOfRegistration, ValidationContext context)
        {
            if (dateOfRegistration > DateTime.Now)
            {
                return new ValidationResult("Date of registration cannot be in the future.");
            }
            return ValidationResult.Success;
        }

        public static ValidationResult ValidateDateOfBirth(DateTime dateOfBirth, ValidationContext context)
        {
            if (dateOfBirth > DateTime.Now)
            {
                return new ValidationResult("Date of birth cannot be in the future.");
            }
            return ValidationResult.Success;
        }
    }
}
